"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { QRCodeCanvas } from "qrcode.react";
import jsPDF from "jspdf";

type ApiResult = {
  trustScore: number;
  riskLevel: "Low Risk" | "Medium Risk" | "High Risk";
  verdict: string;
  explanation: string;
  creditsUsed: number;
  remainingCredits: number | "unlimited";
};

export default function PhoneCheckerPage() {
  const [phone, setPhone] = useState("");
  const [submittedPhone, setSubmittedPhone] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ApiResult | null>(null);
  const [credits, setCredits] = useState<number | "unlimited">(0);

  const router = useRouter();

  /* =========================
     LOAD CREDITS
  ========================= */
  useEffect(() => {
    fetch("/api/credits", { credentials: "include" })
      .then((r) => r.json())
      .then((d) => setCredits(d.credits ?? 0))
      .catch(() => {});
  }, []);

  /* =========================
     CHECK PHONE
  ========================= */
  const handleCheck = async () => {
    if (!phone.trim()) return;

    if (credits !== "unlimited" && credits <= 0) {
      router.push("/pricing");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const res = await fetch("/api/phone-check", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ text: phone.trim() }),
      });

      const data = await res.json();
      if (!res.ok) {
        alert(data?.error || "Unable to analyze phone number");
        return;
      }

      setSubmittedPhone(phone.trim());
      setResult(data);
      setCredits(data.remainingCredits);
      setPhone("");

      window.dispatchEvent(new Event("credits-updated"));
      window.dispatchEvent(new Event("history-updated"));
    } finally {
      setLoading(false);
    }
  };

  /* =========================
     SHARE
  ========================= */
  const shareResult = async () => {
    if (!result) return;

    const text = `Trustverse AI – Phone Check Result

Phone: ${submittedPhone}
Trust Score: ${result.trustScore}/100
Risk Level: ${result.riskLevel}

${result.explanation}

Verified by Trustverse AI
https://www.trustverseai.com`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: "Trustverse AI Phone Report",
          text,
          url: "https://www.trustverseai.com",
        });
        return;
      } catch {}
    }

    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, "_blank");
  };

  /* =========================
     PDF
  ========================= */
  const downloadPDF = () => {
    if (!result) return;

    const pdf = new jsPDF();
    pdf.setFontSize(16);
    pdf.text("Trustverse AI – Phone Verification Report", 10, 20);

    pdf.setFontSize(12);
    pdf.text(`Phone: ${submittedPhone}`, 10, 40);
    pdf.text(`Trust Score: ${result.trustScore}/100`, 10, 50);
    pdf.text(`Risk Level: ${result.riskLevel}`, 10, 60);

    pdf.text("Analysis:", 10, 75);
    pdf.text(result.explanation, 10, 85, { maxWidth: 180 });

    pdf.text("Generated by Trustverse AI", 10, 280);
    pdf.save("trustverse-phone-report.pdf");
  };

  return (
    <div className="max-w-5xl space-y-14">
      {/* HEADER */}
      <div>
        <h1 className="text-3xl font-bold">
          Trustverse AI – Phone Number Checker
        </h1>
        <p className="text-gray-600 max-w-3xl">
          Verify unknown phone numbers using AI-powered trust indicators
          to identify scam, spam, or risky behavior.
        </p>
      </div>

      {/* INPUT */}
      <div className="bg-white p-6 rounded-xl border shadow max-w-xl">
        <input
          value={phone}
          onChange={(e) => setPhone(e.target.value)}
          placeholder="Enter phone number"
          className="w-full border rounded px-4 py-2 mb-4"
        />
        <button
          onClick={handleCheck}
          disabled={loading}
          className="w-full bg-emerald-600 text-white py-2 rounded font-semibold"
        >
          {loading ? "Analyzing…" : "Check Number"}
        </button>
      </div>

      {/* RESULT */}
      {result && (
        <div className="bg-white border rounded-xl shadow">
          <div className="px-6 py-4 border-b">
            <h2 className="text-xl font-bold">
              Trustverse AI – Verification Result
            </h2>
            <p className="text-sm text-green-700">
              ✔ Analysis completed successfully
            </p>
          </div>

          <div className="p-6 space-y-6">
            <span
              className={`inline-block px-3 py-1 rounded-full text-sm font-semibold ${
                result.riskLevel === "Low Risk"
                  ? "bg-green-100 text-green-700"
                  : result.riskLevel === "Medium Risk"
                  ? "bg-yellow-100 text-yellow-700"
                  : "bg-red-100 text-red-700"
              }`}
            >
              {result.riskLevel}
            </span>

            <p><b>Phone:</b> {submittedPhone}</p>

            <p className="text-2xl font-bold">
              Trust Score: {result.trustScore}/100
            </p>

            <div className="w-full bg-gray-200 rounded h-3">
              <div
                className={`h-3 rounded ${
                  result.trustScore >= 80
                    ? "bg-green-500"
                    : result.trustScore >= 60
                    ? "bg-yellow-500"
                    : "bg-red-500"
                }`}
                style={{ width: `${result.trustScore}%` }}
              />
            </div>

            <p className="text-gray-700">{result.explanation}</p>

            <div className="pt-6">
              <QRCodeCanvas
                value={`Phone: ${submittedPhone} | Trust Score: ${result.trustScore}`}
                size={120}
              />
            </div>

            <div className="flex gap-3 flex-wrap pt-2">
              <button
                onClick={shareResult}
                className="bg-blue-600 text-white px-4 py-2 rounded"
              >
                Share
              </button>

              <button
                onClick={downloadPDF}
                className="bg-black text-white px-4 py-2 rounded"
              >
                Download PDF
              </button>

              <button
                onClick={() =>
                  alert("Scam report submitted successfully.")
                }
                className="bg-red-600 text-white px-4 py-2 rounded"
              >
                Report Scam
              </button>
            </div>

            <p className="text-sm text-gray-500">
              Credits Remaining:{" "}
              <b>
                {result.remainingCredits === "unlimited"
                  ? "Unlimited (PRO)"
                  : result.remainingCredits}
              </b>
            </p>
          </div>
        </div>
      )}

      {/* LONG DESCRIPTION */}
      <div className="pt-10 border-t text-gray-700 max-w-4xl">
        <h2 className="text-xl font-semibold mb-4">
          How Trustverse AI Phone Checker Works
        </h2>

        <p>
          Trustverse AI Phone Checker analyzes phone numbers using
          advanced trust indicators, usage pattern evaluation, and
          behavioral risk signals.
        </p>

        <p className="mt-3">
          This tool is ideal for verifying unknown callers, online
          sellers, service providers, or business contacts.
        </p>

        <ul className="list-disc pl-6 mt-4 space-y-2">
          <li>Detect spam and scam phone numbers</li>
          <li>Reduce risk of fraud and financial loss</li>
          <li>Improve personal and business safety</li>
        </ul>

        <p className="text-sm text-gray-500 mt-4">
          Automated analysis only. Always verify independently.
        </p>
      </div>

      {/* =========================
          FAQ SECTION (NEW)
      ========================= */}
      <div className="max-w-4xl space-y-6 border-t pt-10">
        <h2 className="text-2xl font-bold text-gray-900">
          Phone Number Checker – FAQs
        </h2>

        <div>
          <h3 className="font-semibold">
            What type of phone numbers can be analyzed?
          </h3>
          <p className="text-sm text-gray-600">
            You can analyze mobile, landline, VoIP, and international phone
            numbers to assess scam, spam, or fraud risk.
          </p>
        </div>

        <div>
          <h3 className="font-semibold">
            Can a legitimate number show Medium or High Risk?
          </h3>
          <p className="text-sm text-gray-600">
            Yes. New numbers, VoIP services, or limited usage history can
            increase risk indicators even for legitimate users.
          </p>
        </div>

        <div>
          <h3 className="font-semibold">
            Does Trustverse AI block scam calls?
          </h3>
          <p className="text-sm text-gray-600">
            No. Trustverse AI provides intelligence and risk assessment,
            not call blocking. Use call-blocking apps alongside this tool.
          </p>
        </div>

        <div>
          <h3 className="font-semibold">
            Who should use Phone Number Checker?
          </h3>
          <p className="text-sm text-gray-600">
            This tool is ideal for individuals and businesses verifying unknown
            callers before responding, sharing information, or making payments.
          </p>
        </div>
      </div>
    </div>
  );
}
