"use client";

import { useState } from "react";

const faqs = [
  {
    q: "What is Trustverse AI?",
    a: "Trustverse AI is an AI-powered trust and risk intelligence platform designed to help individuals and businesses identify scams, fraud, impersonation attempts, and high-risk online behavior before engagement.",
  },
  {
    q: "How accurate are Trustverse AI tools?",
    a: "Trustverse AI tools use advanced behavioral analysis, pattern recognition, and risk heuristics. While no automated system can guarantee 100% accuracy, our models are designed to surface high-risk indicators that are often missed by manual checks.",
  },
  {
    q: "What is a Trust Score?",
    a: "A Trust Score is a numerical score between 0 and 100 generated by Trustverse AI. Higher scores indicate lower risk, while lower scores suggest potential fraud, impersonation, or scam-related behavior.",
  },
  {
    q: "How do credits work?",
    a: "Each analysis consumes credits depending on the tool used. Free users receive limited credits. PRO users receive unlimited or higher usage depending on their plan. Credit usage is clearly displayed before and after each analysis.",
  },
  {
    q: "Which tools are PRO tools?",
    a: "Advanced tools such as Social Profile Analyzer, Business Checker, Profile Checker, and Advanced AI Analysis are PRO tools and may consume more credits due to deeper intelligence processing.",
  },
  {
    q: "Is my data safe with Trustverse AI?",
    a: "Yes. Trustverse AI does not sell user data. Inputs are analyzed securely and are not used for marketing or shared with third parties. We follow strict data safety and privacy practices.",
  },
  {
    q: "Does Trustverse AI store analyzed data?",
    a: "Basic analysis history is stored for user access and reporting purposes. Sensitive personal data is not publicly exposed and is handled according to our privacy policy.",
  },
  {
    q: "Can Trustverse AI detect all scams?",
    a: "Trustverse AI is designed to identify common scam patterns, manipulation tactics, and risk indicators. However, users should always apply independent judgment, especially for high-value or critical decisions.",
  },
  {
    q: "What should I do if a result shows High Risk?",
    a: "If a result shows High Risk, we strongly recommend avoiding engagement, verifying identities independently, and reporting the case using the built-in scam reporting feature.",
  },
  {
    q: "Can I report scams through Trustverse AI?",
    a: "Yes. You can report suspicious profiles, messages, or businesses directly from the report screen. These reports help improve detection and community safety.",
  },
  {
    q: "Is Trustverse AI available globally?",
    a: "Yes. Trustverse AI is designed for global usage and supports users across different countries and regions.",
  },
  {
    q: "What payment methods does Trustverse AI support?",
    a: "Trustverse AI uses Paddle for secure global payments, supporting international cards, subscriptions, and compliant billing across multiple countries.",
  },
  {
    q: "Do you offer refunds?",
    a: "Refunds are handled according to our refund policy. Since credits are digital and instantly usable, refunds may be limited once credits are consumed.",
  },
  {
    q: "Is Trustverse AI legal or financial advice?",
    a: "No. Trustverse AI provides risk analysis and decision-support insights. It should not be considered legal, financial, or professional advice.",
  },
  {
    q: "How can I contact Trustverse AI support?",
    a: "You can reach out through the Contact page or use the built-in reporting tools for assistance and feedback.",
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="max-w-5xl mx-auto px-4 py-16 space-y-10">
      {/* HEADER */}
      <div>
        <h1 className="text-4xl font-bold text-gray-900">
          Frequently Asked Questions
        </h1>
        <p className="text-gray-600 mt-3 max-w-3xl">
          Find clear answers about Trustverse AI, how our tools work, data safety,
          credits, payments, and platform usage.
        </p>
      </div>

      {/* FAQ LIST */}
      <div className="space-y-4">
        {faqs.map((item, index) => (
          <div
            key={index}
            className="border rounded-xl bg-white shadow-sm"
          >
            <button
              onClick={() =>
                setOpenIndex(openIndex === index ? null : index)
              }
              className="w-full flex justify-between items-center px-6 py-4 text-left"
            >
              <span className="font-semibold text-gray-900">
                {item.q}
              </span>
              <span className="text-xl font-bold text-purple-600">
                {openIndex === index ? "−" : "+"}
              </span>
            </button>

            {openIndex === index && (
              <div className="px-6 pb-4 text-gray-700 leading-relaxed">
                {item.a}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* FOOT NOTE */}
      <div className="pt-10 text-sm text-gray-500 border-t">
        Trustverse AI is a decision-support platform. Always apply independent
        verification for critical financial, legal, or personal decisions.
      </div>
    </div>
  );
}
